// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: api/player.proto

package playerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	LastSeen      int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_api_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_api_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Player) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type CreatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerRequest) Reset() {
	*x = CreatePlayerRequest{}
	mi := &file_api_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerRequest) ProtoMessage() {}

func (x *CreatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_api_player_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlayerRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type CreatePlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerResponse) Reset() {
	*x = CreatePlayerResponse{}
	mi := &file_api_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerResponse) ProtoMessage() {}

func (x *CreatePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerResponse.ProtoReflect.Descriptor instead.
func (*CreatePlayerResponse) Descriptor() ([]byte, []int) {
	return file_api_player_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlayerResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type PlayerGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGetRequest) Reset() {
	*x = PlayerGetRequest{}
	mi := &file_api_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGetRequest) ProtoMessage() {}

func (x *PlayerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGetRequest.ProtoReflect.Descriptor instead.
func (*PlayerGetRequest) Descriptor() ([]byte, []int) {
	return file_api_player_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerGetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PlayerGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGetResponse) Reset() {
	*x = PlayerGetResponse{}
	mi := &file_api_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGetResponse) ProtoMessage() {}

func (x *PlayerGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGetResponse.ProtoReflect.Descriptor instead.
func (*PlayerGetResponse) Descriptor() ([]byte, []int) {
	return file_api_player_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerGetResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

var File_api_player_proto protoreflect.FileDescriptor

const file_api_player_proto_rawDesc = "" +
	"\n" +
	"\x10api/player.proto\x12\x06player\"c\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\"C\n" +
	"\x13CreatePlayerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\">\n" +
	"\x14CreatePlayerResponse\x12&\n" +
	"\x06player\x18\x01 \x01(\v2\x0e.player.PlayerR\x06player\"\"\n" +
	"\x10PlayerGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x11PlayerGetResponse\x12&\n" +
	"\x06player\x18\x01 \x01(\v2\x0e.player.PlayerR\x06player2\x9a\x01\n" +
	"\vgRPCService\x12I\n" +
	"\fCreatePlayer\x12\x1b.player.CreatePlayerRequest\x1a\x1c.player.CreatePlayerResponse\x12@\n" +
	"\tGetPlayer\x12\x18.player.PlayerGetRequest\x1a\x19.player.PlayerGetResponseB\x14Z\x12study/api;playerpbb\x06proto3"

var (
	file_api_player_proto_rawDescOnce sync.Once
	file_api_player_proto_rawDescData []byte
)

func file_api_player_proto_rawDescGZIP() []byte {
	file_api_player_proto_rawDescOnce.Do(func() {
		file_api_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_player_proto_rawDesc), len(file_api_player_proto_rawDesc)))
	})
	return file_api_player_proto_rawDescData
}

var file_api_player_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_player_proto_goTypes = []any{
	(*Player)(nil),               // 0: player.Player
	(*CreatePlayerRequest)(nil),  // 1: player.CreatePlayerRequest
	(*CreatePlayerResponse)(nil), // 2: player.CreatePlayerResponse
	(*PlayerGetRequest)(nil),     // 3: player.PlayerGetRequest
	(*PlayerGetResponse)(nil),    // 4: player.PlayerGetResponse
}
var file_api_player_proto_depIdxs = []int32{
	0, // 0: player.CreatePlayerResponse.player:type_name -> player.Player
	0, // 1: player.PlayerGetResponse.player:type_name -> player.Player
	1, // 2: player.gRPCService.CreatePlayer:input_type -> player.CreatePlayerRequest
	3, // 3: player.gRPCService.GetPlayer:input_type -> player.PlayerGetRequest
	2, // 4: player.gRPCService.CreatePlayer:output_type -> player.CreatePlayerResponse
	4, // 5: player.gRPCService.GetPlayer:output_type -> player.PlayerGetResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_player_proto_init() }
func file_api_player_proto_init() {
	if File_api_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_player_proto_rawDesc), len(file_api_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_player_proto_goTypes,
		DependencyIndexes: file_api_player_proto_depIdxs,
		MessageInfos:      file_api_player_proto_msgTypes,
	}.Build()
	File_api_player_proto = out.File
	file_api_player_proto_goTypes = nil
	file_api_player_proto_depIdxs = nil
}
